# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    #config.vm.network "public_network"
    config.vm.box = "centos/7"
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
    end
    
    config.vm.define "сentralserver" do |server|
        server.vm.hostname = "server"
        server.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "int"
        server.vm.provision "file", source: "update_package.sh", destination: "/tmp/update_package.sh"
        server.vm.provision "file", source: "hosts.txt", destination: "/tmp/hosts.txt"
        server.vm.provision "shell", inline: <<-SHELL
        echo -e "\n"|ssh-keygen -t rsa -N ""                      
        yum install sshpass -y
        cd /tmp && mv hosts.txt update_package.sh /root/
        SHELL
    end

    config.vm.define "server2" do |server2|
        server2.vm.hostname = "server2"
        server2.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "int"
        server2.vm.provision "shell", inline: <<-SHELL
        sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
        echo "root" | passwd --stdin root
        yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
        SHELL
    end
    
    config.vm.define "server3" do |server3|
        server3.vm.hostname = "server3"
        server3.vm.network "private_network", ip: "192.168.50.12", virtualbox__intnet: "int"
        server3.vm.provision "shell", inline: <<-SHELL
        sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
        echo "root" | passwd --stdin root
        SHELL
    end

end